# Generated by Django 4.2.15 on 2024-08-15 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("products", models.JSONField(default=list)),
                ("status", models.CharField(default="pending", max_length=20)),
                ("date_of_purchase", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
