# Generated by Django 4.2.15 on 2024-08-15 08:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orders",
            name="total",
            field=models.IntegerField(default=0),
        ),
    ]
