# Generated by Django 4.2.15 on 2024-08-26 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("order", "0002_orders_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="products",
        ),
        migrations.AddField(
            model_name="orders",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orders",
            name="total",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="OrdersItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.PositiveIntegerField()),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="order.orders",
                    ),
                ),
            ],
        ),
    ]
